version: '3'

services:
  db:
    image: postgres
    volumes:
      - ${ACTIONS_POSTGRES_DIR}:/var/lib/postgresql/data/
    env_file:
      - web-dev.env
    networks:
      - db_network
    command: -p 5433
  web:
    build: .
    env_file:
      - web-dev.env 
    command: gunicorn --bind :5000 actions.wsgi:application
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    depends_on:
      - db
    networks:  # <-- here
      - nginx_network
      - db_network
  nginx:
    image: nginx:1.16.1
    depends_on:
      - web
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ${NGINX_CONFIG}:/etc/nginx/conf.d
      - ${NGINX_CERTS_DIR}:/etc/nginx/certs
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    networks:  # <-- here
      - nginx_network

networks:  # <-- and here
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge

volumes:
  static_volume:
  media_volume:
