version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    env_file:
      - web-dev.env 
    command: gunicorn --bind :8000 actions.wsgi:application
    volumes:
      - .:/code
    depends_on:
      - db
    networks:  # <-- here
      - nginx_network
  nginx:
    image: nginx:1.16.1
    depends_on:
      - web
    ports:
      - "${NGINX_PORT}:80"
      - "443:443"
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    networks:  # <-- here
      - nginx_network

networks:  # <-- and here
  nginx_network:
    driver: bridge