nginx:
    image: nginx:1.16.1
    depends_on:
      - web
    ports:
      - "${NGINX_PORT}:80"
      - "443:443"
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ${NGINX_CERTS_DIR}:/etc/nginx/certs
    networks:  # <-- here
      - nginx_network
certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:${NGINX_CERTS_DIR}
      - certbot-var:/var/lib/letsencrypt
      - web-root:${CERTBOX_WEBROOT}
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=${CERTBOT_WEBROOT} --email ${CERTBOT_EMAIL} --agree-tos --no-eff-email --staging -d ${ACTIONS_API_DOMAIN}.com  -d www.${ACTIONS_API_DOMAIN}.com 

volumes:
  certbot-etc:
  certbot-var:
  web-root: