# Generated by Django 3.0 on 2019-12-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='end_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='actioncard',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
