# Generated by Django 3.0 on 2019-12-07 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions_app', '0002_auto_20191206_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='actioncard',
            name='actions',
            field=models.ManyToManyField(to='actions_app.Action'),
        ),
        migrations.AlterField(
            model_name='action',
            name='description',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=500)),
                ('action_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='actions_app.ActionCard')),
                ('actions', models.ManyToManyField(to='actions_app.Action')),
            ],
        ),
    ]
