# Generated by Django 3.0 on 2019-12-21 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actions_app', '0003_auto_20191207_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='survey_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='action_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='survey_responses', to='actions_app.ActionCard'),
        ),
    ]
