# Generated by Django 3.0 on 2019-12-12 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions_app', '0003_auto_20191207_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='action_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='survey_responses', to='actions_app.ActionCard'),
        ),
    ]
