# Generated by Django 2.2.9 on 2019-12-30 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions_app', '0004_auto_20191221_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='date_type',
            field=models.CharField(choices=[['ON', 'on'], ['BEFORE', 'before'], ['RANGE', 'range'], ['NONE', 'none']], default='NONE', max_length=100),
        ),
        migrations.AddField(
            model_name='action',
            name='geography_type',
            field=models.CharField(choices=[['LOCAL', 'Local'], ['REGIONAL', 'Regional'], ['STATE', 'State'], ['NATIONAL', 'National'], ['UNDEFINED', 'Undefined']], default='UNDEFINED', max_length=100),
        ),
        migrations.AddField(
            model_name='action',
            name='tags',
            field=models.ManyToManyField(to='actions_app.Tag'),
        ),
    ]
