# Generated by Django 2.2.9 on 2020-01-07 11:20

import datetime
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('actions_app', '0006_auto_20191231_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='tags',
        ),
        migrations.AddField(
            model_name='action',
            name='taggit',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='actioncard',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
