# Generated by Django 2.2.9 on 2020-02-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions_app', '0007_auto_20200107_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actioncard',
            name='actions',
            field=models.ManyToManyField(blank=True, to='actions_app.Action'),
        ),
    ]
