# Generated by Django 2.2.11 on 2020-03-28 13:28

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('actions_app', '0008_auto_20200202_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
