# Generated by Django 2.2.11 on 2020-03-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions_app', '0009_auto_20200328_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='slug',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
